language: php
sudo: false

php:
  - 7.1
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer update --no-scripts
  - composer dump-autoload

script:
  - php bin/page.php get /
