language: php
sudo: false
php:
  - 7
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
before_script:
  - composer self-update
  - composer update --no-scripts
  - composer dump-autoload
script:
  - php bin/page.php get /
